### ISSUE TITLE
Unable to build web app with ES client package

### ISSUE THREAD

**Issue by robin-dojo** [DISCOOS/eventstore-client-dart#6] opened 2022-11-02 13:40 UTC
It looks like there might be an issue with the compatibility with the latest dart packages. Getting the following errors when trying to build web app - MacOS is building and running fine:

```Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use
'dart compile js' instead.
../../develop/flutter/.pub-cache/hosted/pub.dartlang.org/eventstore_client-0.6.1/lib/src/core/constants.d
art:7:13:
Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
const Max = 9223372036854775807;
            ^^^^^^^^^^^^^^^^^^^
../../develop/flutter/.pub-cache/hosted/pub.dartlang.org/eventstore_client-0.6.1/lib/src/core/client_base
.dart:205:25:
Error: The argument type 'X509Certificate/*1*/' can't be assigned to the parameter type
'X509Certificate/*2*/'.
 - 'X509Certificate/*1*/' is from 'dart:io'.
 - 'X509Certificate/*2*/' is from 'package:universal_io/src/io/secure_socket.dart'
 ('../../develop/flutter/.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.4/lib/src/io/secure_socket.d
 art').
                        cert,
                        ^
../../develop/flutter/.pub-cache/hosted/pub.dartlang.org/eventstore_client-0.6.1/lib/src/core/helpers.dar
t:133:53:
Error: The argument type 'X509Certificate/*1*/' can't be assigned to the parameter type
'X509Certificate/*2*/'.
 - 'X509Certificate/*1*/' is from 'package:universal_io/src/io/secure_socket.dart'
 ('../../develop/flutter/.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.4/lib/src/io/secure_socket.d
 art').
 - 'X509Certificate/*2*/' is from 'dart:io'.
        return channelCredentials.onBadCertificate!(cert, host);
                                                    ^
../../develop/flutter/.pub-cache/hosted/pub.dartlang.org/eventstore_client-0.6.1/lib/src/core/helpers.dar
t:144:7:
Error: A value of type 'bool Function(X509Certificate, String, int)?' can't be assigned to a variable of
type 'bool Function(X509Certificate, String, int)' because 'bool Function(X509Certificate, String, int)?'
is nullable and 'bool Function(X509Certificate, String, int)' isn't.
 - 'X509Certificate' is from 'package:universal_io/src/io/secure_socket.dart'
 ('../../develop/flutter/.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.4/lib/src/io/secure_socket.d
 art').
    ).onBadCertificate;
      ^
Error: Compilation failed.

**Comment by kengu** [comment] 2022-11-02 16:11
Hi! Did it work earlier for web-targets? I would not think so based on the errors above. I haven't tested it myself on web-targets, but it seems like the MAX literal is not possible to represent as an integer i js. I'll investigate and come back to you.

**Comment by kengu** [comment] 2022-11-02 17:04
Bug confirmed with `flutter run -d chrome`, investigating further

**Comment by kengu** [comment] 2022-11-02 19:13
The `X509Certificate` errors are there because [eventstore_client](https://pub.dev/packages/eventstore_client) does not _as of now_ support web, as [shown here in the scoring section](https://pub.dev/packages/eventstore_client/score)
![Screenshot 2022-11-02 at 20 07 00](https://user-images.githubusercontent.com/866528/199579948-d3ad992f-5a7b-4761-bb6a-93a4e8721c32.png)
I'm not sure how I will introduce support for web, probably following the pattern in the [grpc](https://pub.dev/packages/grpc) package.

**Comment by kengu** [comment] 2022-11-02 19:32
@robin-dojo I can't promise when web support is available, but I am working on it.

**Comment by kengu** [comment] 2022-11-03 09:56
@robin-dojo gRPC-web is now [supported in master](https://github.com/DISCOOS/eventstore-client-dart). I'll release a new version to pub.dev soon. 

**NOTE**
[EventStoreDB](https://github.com/EventStore/EventStore) does not support the [gRPC-web protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) directly ([in-process proxy](https://github.com/grpc/grpc-web/blob/master/doc/in-process-proxy.md)). The EventStore team could add in-process proxy support using [Grpc.AspNetCore.Web](https://www.nuget.org/packages/Grpc.AspNetCore.Web), but I doubt they will prioritize this because gRCP-web have limited streaming support (details below). If you plan to connect directly to EventStoreDB from a browser, you need to configure a gRCP-web proxy in front of EventStoreDB, that translates between [native gRPC](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) and gRPC-web protocols automatically (see official [Google implementation of grpc-web](https://github.com/grpc/grpc-web)). 

**IMPORTANT!** gRPC-web have [limited streaming support](https://github.com/grpc/grpc-web#streaming-support). Especially bidirectional streams (both RPC requests and responses are sent and received using streams) which EventStoreDB use for Append-operations, are not supported by the gRPC-web protocol. When browser-support for [Streams](https://streams.spec.whatwg.org/) is high enough ([see global coverage](https://caniuse.com/streams)), the gRCP-web protocol will become optional and web clients will also be able to use the native gRPC protocol.

**Choices**
You have three technical different options to choose from when connecting to EventStoreDB from a browser. 

If you only need to read events, then one of these options is sufficient
  - use Envoy as reverse proxy (official solution, Front + Sidecar Proxy, see [conceptual example using AWS](https://aws.amazon.com/blogs/compute/setting-up-an-envoy-front-proxy-on-amazon-ecs/))
  - use another reverse proxy from the community, see [proxying gRPC-web](https://microsoft.github.io/reverse-proxy/articles/grpc.html#grpc-web) with [YARP](https://microsoft.github.io/reverse-proxy/) from Microsoft (open source)
  - implement an [in-process proxy](https://github.com/grpc/grpc-web/blob/master/doc/in-process-proxy.md) in EventStoreDB yourself 

If you also need to support appending events from the browser, then you need to make a custom gRPC server between the gRCP-web proxy (Envoy or in-process) and EventStoreDB. This custom gRPC server must translate the bi-directional `Append` command exposed by EventStoreDB to a command exposed by the custom gRCP server that is supported by the gRPC-web protocol. You could do this by implementing an `Append` command with an unary request (all events in one request) that returns a stream of responses (same as the `Append` command exposed by EventStoreDB does). This command _is_ supported by gRCP-web and _should work_ (in theory, I have not tested it myself). You would need to repeat this for all EventStore gRPC service commands that are bidirectional, which is a big undertaking. 

**My advice**
If you need Append-support from the browser, I think the better solution is to wait for the official support of [native gRPC](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) that use [Streams](https://streams.spec.whatwg.org/). I don't know when this will happen, but the ([global coverage](https://caniuse.com/streams)) is ~94% now. See the [roadmap for full streaming support](https://github.com/grpc/grpc-web/blob/master/doc/streaming-roadmap.md) for official information.

**Comment by robin-dojo** [comment] 2022-11-03 12:46
Thanks, @kengu - will try out 0.7.0 when it is released.

For my needs, the web interface will not need to append streams directly as we have an API service for this, but other platforms will require it as they will not always interact with the API :)

**Comment by kengu** [comment] 2022-11-05 16:48
Fixed in master. See [flutter_echo_app](https://github.com/DISCOOS/eventstore-client-dart/tree/master/packages/eventstore_client#readme) for example of grpc-web protocol usage, and [tool/grpc/bridge](https://github.com/DISCOOS/eventstore-client-dart/tree/master/packages/eventstore_client/tool/grpc/bridge#readme) for example of how the infrastructure is set up locally for testing.

**Closed as completed by kengu** 2022-11-05 16:48 UTC
Labels: bug
